<a href="https://colab.research.google.com/github/samridz8/EigenValueEigenVector/blob/main/EigenValueEigenVector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
def normalize(x):
    fac = abs(x).max()
    x_n = x /fac
    return fac, x_n
x = np.array([1,1,1])
a = np.array([[1,1,3],(1,5,1),(3,1,1)])

for i in range(10):
    x = np.dot(a,x)
    lambda_1, x = normalize(x)
    print(lambda_1,x)
print('eigenvalue:',lambda_1)
print('eigenvector:',x)

7 [0.71428571 1.         0.71428571]
6.428571428571429 [0.6 1.  0.6]
6.199999999999999 [0.5483871 1.        0.5483871]
6.096774193548388 [0.52380952 1.         0.52380952]
6.0476190476190474 [0.51181102 1.         0.51181102]
6.0236220472440944 [0.50588235 1.         0.50588235]
6.011764705882353 [0.50293542 1.         0.50293542]
6.00587084148728 [0.50146628 1.         0.50146628]
6.002932551319649 [0.50073278 1.         0.50073278]
6.001465559355154 [0.5003663 1.        0.5003663]
eigenvalue: 6.001465559355154
eigenvector: [0.5003663 1.        0.5003663]


In [ ]:
import numpy as np
I = np.array([[1,-3,3],[3,-5,3],[6,-6,4]])
print("\n Given matrix: \n", I)
w,v = np.linalg.eig(I)
print("\n Eigen values: \n", w)
print("\n Eigen vector:\n", v)


 Given matrix: 
 [[ 1 -3  3]
 [ 3 -5  3]
 [ 6 -6  4]]

 Eigen values: 
 [ 4.+0.00000000e+00j -2.+1.10465796e-15j -2.-1.10465796e-15j]

 Eigen vector:
 [[-0.40824829+0.j          0.24400118-0.40702229j  0.24400118+0.40702229j]
 [-0.40824829+0.j         -0.41621909-0.40702229j -0.41621909+0.40702229j]
 [-0.81649658+0.j         -0.66022027+0.j         -0.66022027-0.j        ]]


In [ ]:
f1 = lambda x,y,z: (17-y+2*z)/20
f2 = lambda x,y,z: (-18-3*x+z)/20
f3 = lambda x,y,z: (25-2*x+3*y)/20

x0 = 0
y0 = 0
z0 = 0
count= 1
e= float(input('Enter tolerable error: '))
print('\n count\t x\t y\t z\n')

condition = True
while condition:
   x1 = f1(x0,y0,z0)
   y1 = f2(x0,y0,z0)
   z1= f3(x0,y0,z0)
   print('%d \t %0.2f \t%0.2f \t%0.2f \n' %(count,x1,y1,z1))
   e1 = abs(x0-x1);
   e2 = abs(y0-y1);
   e3 = abs(z0-z1);

   count += 1
   x0 = x1
   y0 = y1
   z0 = z1

   condition =  e1>e and e2>e and e3>e

print('\nsolution: x=%0.2f, y=%0.2f and z=%0.2f\n'% (x1,y1,z1))



Enter tolerable error: 1

 count	 x	 y	 z

1 	 0.85 	-0.90 	1.25 


solution: x=0.85, y=-0.90 and z=1.25

